config/routes.rb
L2adena::Application.routes.draw do

  match '/game/:action/(/:id)' => 'game_accounts'

  match '/signin' => 'services#signin'
  match '/signout' => 'services#signout'

  match '/auth/:service/callback' => 'services#create'
  match '/auth/failure' => 'services#failure'

  namespace 'admin' do
    resources :home, :only => [:index] do
      collection do
      end
    end

    resources :user
    resources :news
    resources :tickets
    resources :ticket_replies

    resources :game_servers do
      member do
        get 'move_up'
        get 'move_down'
      end
    end

    resources :pages do
      member do
        get 'move_up'
        get 'move_down'
      end
    end

    root :to => 'home#index'
  end
  resources :tickets do
    collection do
      post 'preview'
    end
  end

  resources :ticket_replies
  resources :services, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'signup'
      get 'register'
      post 'newaccount'
      get 'failure'
    end
  end
  
  resources :users, :only => [:index] do
    member do
      get 'edit_profile'
      post 'update_profile'
    end

    collection do
      get 'dismiss_newbie_bar'
      get 'undismiss_newbie_bar'
    end
  end

  match '/accounts/:action' => 'accounts'

  match '(/:id)' => 'home#show_page'

  root :to => 'home#index'

end

app/views/admin/pages/_form.html.erb
<%= stylesheet_link_tag '/markitup/skins/markitup/style' %>
<%= stylesheet_link_tag '/markitup/sets/html/style' %>

<%= javascript_include_tag '/markitup/jquery.markitup.js' %>
<%= javascript_include_tag '/markitup/sets/html/set.js' %>

<script type="text/javascript">
  $(document).ready(function() {
      $('#page_content').markItUp(mySettings);
      });
</script>
  <%= f.label :name %><br />
  <%= f.text_field :name %><br />

  <%= f.label :permalink %><br />
  <%= f.text_field :permalink %><br />

  <%= f.label :content %><br />
  <%= f.text_area :content %><br />

  <%= f.label :visible %> <%= f.check_box :visible %><br />

app/views/admin/pages/edit.html.erb
<h1>Edit Page</h1>

<% if @page.errors.any? %>
  <%= error_messages_for(@page) %>
<% end %>

<%= form_for(@page, :url => {:controller => '/admin/pages', :action => 'update', :id => @page.id}) do |f| %>
  <%= render(:partial => 'form', :locals => {:f => f}) %>
  <%= f.submit %>
<% end %>

app/views/admin/pages/index.html.erb
<h1>Manage Pages</h1>

<table>
  <tr>
    <th>Page Title</th>
    <th>Permalink</th>
    <th>Position</th>
    <th>Visible</th>
    <th>Action</th>
  </tr>

  <% @pages.each do |page| %>
    <tr>
      <td><%= page.name %></td>
      <td><%= page.permalink %></td>
      <td><%= page.position %></td>
      <td><%= page.visible %></td>
      <td>
        <%= link_to("Move Up", move_up_admin_page_path(page)) %>
        <%= link_to("Move Down", move_down_admin_page_path(page)) %>
        <%= link_to("Show", admin_page_path(page)) %>
        <%= link_to("Edit", edit_admin_page_path(page)) %>
        <%= link_to("Destroy", admin_page_path(page), :confirm => 'Are you sure you wish to permalantly delete this page', :method => :delete) %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to("Add New Page", new_admin_page_path) %>

app/views/admin/pages/new.html.erb
<h1>Create new Page</h1>

<% if @page.errors.any? %>
  <%= error_messages_for(@page) %>
<% end %>

<%= form_for(@page, :url => {:controller => '/admin/pages', :action => 'create'}) do |f| %>
  <%= render(:partial => 'form', :locals => {:f => f}) %>
  <%= f.submit %>
<% end %>

app/views/admin/pages/show.html.erb
<h1>Show Page <%= @page.name %></h1>
<h4><%= link_to("Edit this Page", edit_admin_page_path(@page)) %></h4>

<%= raw(@page.content) %>