config/routes.rb
L2adena::Application.routes.draw do

  match '/game/:action/(/:id)' => 'game_accounts'

  match '/signin' => 'services#signin'
  match '/signout' => 'services#signout'

  match '/auth/:service/callback' => 'services#create'
  match '/auth/failure' => 'services#failure'

  namespace 'admin' do
    resources :home, :only => [:index] do
      collection do
      end
    end

    resources :user
    resources :news
    resources :tickets
    resources :ticket_replies

    resources :game_servers do
      member do
        get 'move_up'
        get 'move_down'
      end
    end

    resources :pages do
      member do
        get 'move_up'
        get 'move_down'
      end
    end

    root :to => 'home#index'
  end
  resources :tickets do
    collection do
      post 'preview'
    end
  end

  resources :ticket_replies
  resources :services, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'signup'
      get 'register'
      post 'newaccount'
      get 'failure'
    end
  end
  
  resources :users, :only => [:index] do
    member do
      get 'edit_profile'
      post 'update_profile'
    end

    collection do
      get 'dismiss_newbie_bar'
      get 'undismiss_newbie_bar'
    end
  end

  match '/accounts/:action' => 'accounts'

  match '(/:id)' => 'home#show_page'

  root :to => 'home#index'

end

app/models/news.rb
class News < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :name
  validates_presence_of :content

end

app/controllers/admin/news_controller.rb
class Admin::NewsController < Admin::AdminController

  def index
    @news_items = News.paginate(:page => params[:page]).order("created_at desc")
  end

  def show
    @news = News.find(params[:id])
  end

  def new
    @news = News.new
  end

  def create
    @news = News.new

    @news.name = params[:news][:name]
    @news.user_id = current_user.id
    @news.content = params[:news][:content]

    if @news.save
      flash[:success] = "News has been posted"
      redirect_to admin_news_index_path
    else
      render('new')
    end
  end

  def edit
    @news = News.find(params[:id])
  end

  def update
    @news = News.find(params[:id])

    @news.name = params[:news][:name]
    @news.content = params[:news][:content]

    if @news.save
      flash[:success] = "News item has been updated"
      redirect_to admin_news_index_path
    else
      render('edit')
    end
  end

  def destroy
    news = News.find(params[:id])
    news.delete
    flash[:success] = "The news item has been deleted"
    redirect_to admin_news_index_path
  end

end

app/helpers/admin/news_helper.rb
module Admin::NewsHelper
end

app/views/admin/news/_form.html.erb
<%= stylesheet_link_tag '/markitup/markitup/skins/markitup/style' %>
<%= stylesheet_link_tag '/markitup/markitup/sets/default/style' %>

<%= javascript_include_tag '/markitup/markitup/jquery.markitup.js' %>
<%= javascript_include_tag '/markitup/markitup/sets/default/set.js' %>

<script type="text/javascript">
  $(document).ready(function() {
      $('#news_content').markItUp(mySettings);
      });
</script>
<%= f.label :name %><br />
<%= f.text_field :name %><br />

<%= f.label :content %><br />
<%= f.text_area :content %><br />

app/views/admin/news/edit.html.erb
<h1>Edit News Item</h1>

<% if @news.errors.any? %>
  <%= error_messages_for(@news) %>
<% end %>

<%= form_for(@news, :url => {:controller => '/admin/news', :action => 'update', :id => @news.id}) do |f| %>
  <%= render(:partial => 'form', :locals => {:f => f}) %>
  <%= f.submit %>
<% end %>

app/views/admin/news/index.html.erb
<h1>Manage News Items</h1>


<table>
  <tr>
    <th>Date</th>
    <th>Title</th>
    <th>User</th>
    <th>Actions</th>
  </tr>

  <% @news_items.each do |news| %>
    <tr>
      <td><%= news.created_at %></td>
      <td><%= news.name %></td>
      <td><%= news.user.username %></td>
      <td>
        <%= link_to("Show", admin_news_path(news)) %>
        <%= link_to("Edit", edit_admin_news_path(news)) %>
        <%= link_to("Destroy", admin_news_path(news), :confirm => 'Are you sure you wish to permanently delete this record?', :method => :delete) %>
      </td>
    </tr>
  <% end %>
</table>
<%= will_paginate @news_items %>

<%= link_to("New News Item", new_admin_news_path) %>

app/views/admin/news/new.html.erb
<h1>Create News</h1>

<% if @news.errors.any? %>
  <%= error_messages_for(@news) %>
<% end %>
<%= form_for(@news, :url => {:controller => '/admin/news', :action => 'create'}) do |f| %>
  <%= render(:partial => 'form', :locals => {:f => f}) %>
  <%= f.submit %>
<% end %>

app/views/admin/news/show.html.erb
<h1>Show News Item</h1>

<h2><%= @news.name %>(<%= link_to("Edit", edit_admin_news_path(@news)) %>)</h2>

<p><%= raw(@news.content) %></p>