config/routes.rb
L2adena::Application.routes.draw do

  match '/game/:action/(/:id)' => 'game_accounts'

  match '/signin' => 'services#signin'
  match '/signout' => 'services#signout'

  match '/auth/:service/callback' => 'services#create'
  match '/auth/failure' => 'services#failure'

  namespace 'admin' do
    resources :home, :only => [:index] do
      collection do
      end
    end

    resources :user
    resources :news
    resources :tickets
    resources :ticket_replies

    resources :game_servers do
      member do
        get 'move_up'
        get 'move_down'
      end
    end

    resources :pages do
      member do
        get 'move_up'
        get 'move_down'
      end
    end

    root :to => 'home#index'
  end
  resources :tickets do
    collection do
      post 'preview'
    end
  end

  resources :ticket_replies
  resources :services, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'signup'
      get 'register'
      post 'newaccount'
      get 'failure'
    end
  end
  
  resources :users, :only => [:index] do
    member do
      get 'edit_profile'
      post 'update_profile'
    end

    collection do
      get 'dismiss_newbie_bar'
      get 'undismiss_newbie_bar'
    end
  end

  match '/accounts/:action' => 'accounts'

  match '(/:id)' => 'home#show_page'

  root :to => 'home#index'

end

app/models/game_server.rb
class GameServer < ActiveRecord::Base

  validates_presence_of :name
  validates_presence_of :gameserver_hostname
  validates_presence_of :gameserver_port
  validates_presence_of :gameserver_database_hostname
  validates_presence_of :gameserver_database_port
  validates_presence_of :gameserver_database_username
  validates_presence_of :gameserver_database_password
  validates_presence_of :gameserver_database_name

  validate :database_connectable
  validate :is_l2j_gameserver_database

  acts_as_list

  private

  def database_connectable
    begin
      client = Mysql2::Client.new(:host => self.gameserver_database_hostname,
                                  :port => self.gameserver_database_port,
                                  :username => self.gameserver_database_username,
                                  :password => self.gameserver_database_password,
                                  :database => self.gameserver_database_name)
    rescue Exception => e
      errors.add(:base, "Please check your connection info, error was #{e.message}")
    end
  end

  # do a sanity check to see if the database has tables that I expect to have
  # in a l2j gameserver database
  def is_l2j_gameserver_database
    begin
      client = Mysql2::Client.new(:host => self.gameserver_database_hostname,
                                  :port => self.gameserver_database_port,
                                  :username => self.gameserver_database_username,
                                  :password => self.gameserver_database_password,
                                  :database => self.gameserver_database_name)
      begin
        client.query("DESCRIBE characters")
        client.query("DESCRIBE char_templates")
      rescue Exception => e2
        errors.add(:base, "This does not look like a valid l2j gameserver database")
      end
    rescue Exception => e
      # ignore everything since we check for database connectivity in another
      # method
    end
  end

end

app/controllers/admin/game_servers_controller.rb
class Admin::GameServersController < Admin::AdminController

  before_filter :check_gameserver_information_access

  def index
    @game_servers = GameServer.all
  end

  def new
    @game_server = GameServer.new
    @game_server.gameserver_port = 7777
    @game_server.gameserver_database_port = 3306
  end

  def create
    @game_server = GameServer.new

    @game_server.name = params[:game_server][:name]
    @game_server.gameserver_hostname = params[:game_server][:gameserver_hostname]
    @game_server.gameserver_port = params[:game_server][:gameserver_port].to_i
    @game_server.gameserver_database_hostname = params[:game_server][:gameserver_database_hostname]
    @game_server.gameserver_database_port = params[:game_server][:gameserver_database_port].to_i
    @game_server.gameserver_database_username = params[:game_server][:gameserver_database_username]
    @game_server.gameserver_database_password = params[:game_server][:gameserver_database_password]
    @game_server.gameserver_database_name = params[:game_server][:gameserver_database_name]
    @game_server.visible = params[:game_server][:visible]

    if @game_server.save
      flash[:notice] = "Game server has been added"
      redirect_to admin_game_servers_path
    else
      render('admin/game_servers/new')
    end
  end

  def edit
    @game_server = GameServer.find(params[:id])
  end

  def update
    @game_server = GameServer.find(params[:id])

    @game_server.name = params[:game_server][:name]
    @game_server.gameserver_hostname = params[:game_server][:gameserver_hostname]
    @game_server.gameserver_port = params[:game_server][:gameserver_port].to_i
    @game_server.gameserver_database_hostname = params[:game_server][:gameserver_database_hostname]
    @game_server.gameserver_database_port = params[:game_server][:gameserver_database_port].to_i
    @game_server.gameserver_database_username = params[:game_server][:gameserver_database_username]
    @game_server.gameserver_database_password = params[:game_server][:gameserver_database_password]
    @game_server.gameserver_database_name = params[:game_server][:gameserver_database_name]
    @game_server.visible = params[:game_server][:visible]

    if @game_server.save
      flash[:notice] = "Game server information has been updated"
      redirect_to admin_game_servers_path
    else
      render('admin/game_servers/edit')
    end
  end

  def destroy
    game_server = GameServer.find(params[:id])
    game_server.destroy
    flash[:notice] = "Game server information has been removed"
    redirect_to admin_game_servers_path
  end

  def move_up
    @game_server = GameServer.find(params[:id])
    @game_server.move_higher
    redirect_to admin_game_servers_path
  end

  def move_down
    @game_server = GameServer.find(params[:id])
    @game_server.move_lower
    redirect_to admin_game_servers_path
  end

  private

  def check_gameserver_information_access
    check_access(:gameserver_information)
  end

end

app/helpers/admin/game_servers_helper.rb
module Admin::GameServersHelper
end

app/views/admin/game_servers/_form.html.erb
  <%= f.label :name, "Server name (Visible to public)" %><br />
  <%= f.text_field :name %><br />

  <%= f.label :gameserver_hostname %><br />
  <%= f.text_field :gameserver_hostname %><br />

  <%= f.label :gameserver_port %><br />
  <%= f.text_field :gameserver_port %><br />

  <%= f.label :gameserver_database_hostname %><br />
  <%= f.text_field :gameserver_database_hostname %><br />

  <%= f.label :gameserver_database_port %><br />
  <%= f.text_field :gameserver_database_port %><br />

  <%= f.label :gameserver_database_username %><br />
  <%= f.text_field :gameserver_database_username %><br />

  <%= f.label :gameserver_database_password %><br />
  <%= f.text_field :gameserver_database_password %><br />

  <%= f.label :gameserver_database_name %><br />
  <%= f.text_field :gameserver_database_name %><br />

  <%= f.check_box :visible %>
  <%= f.label :visible, "Server status visible to public?" %><br />

app/views/admin/game_servers/edit.html.erb
<%= link_to "<< Back to Game Servers", admin_game_servers_path %>

<h1>Edit: Game Server</h1>
<%= error_messages_for @game_server %>
<%= form_for(@game_server, :url => admin_game_server_path(@game_server)) do |f| %>
  <%= render(:partial => 'form', :locals => {:f => f}) %>

  <%= f.submit %>
<% end %>

app/views/admin/game_servers/index.html.erb
<h1>Manage Game Servers</h1>
<p>Adding gameserver information here will allow this application to manage ingame
characters through the administration panel</p>

<% if @game_servers.any? %>
  <table>
    <tr>
      <th>Server name</th>
    </tr>
    <% @game_servers.each do |server| %>
    <tr>
      <td><%= server.name %></td>
      <td>
        <%= link_to "Edit", edit_admin_game_server_path(server) %>
        <%= link_to "Move Up", move_up_admin_game_server_path(server) %>
        <%= link_to "Move Down", move_down_admin_game_server_path(server) %>
        <%= link_to "Delete", admin_game_server_path(server), {:method => :delete, :confirm => "Are you sure?"} %>
      </td>
    </tr>
    <% end %>
  </table>
<% else %>
  <p>There are currently no game servers</p>
<% end %>

<%= link_to "Add new Gameserver", new_admin_game_server_path %>

app/views/admin/game_servers/new.html.erb
<%= link_to "<< Back to Game Servers", admin_game_servers_path %>

<h1>Add new Game Server</h1>
<%= error_messages_for @game_server %>
<%= form_for(@game_server, :url => admin_game_servers_path) do |f| %>
  <%= render(:partial => 'form', :locals => {:f => f}) %>

  <%= f.submit %>
<% end %>