config/routes.rb
L2adena::Application.routes.draw do

  match '/game/:action/(/:id)' => 'game_accounts'

  match '/signin' => 'services#signin'
  match '/signout' => 'services#signout'

  match '/auth/:service/callback' => 'services#create'
  match '/auth/failure' => 'services#failure'

  namespace 'admin' do
    resources :home, :only => [:index] do
      collection do
      end
    end

    resources :user
    resources :news
    resources :tickets
    resources :ticket_replies

    resources :game_servers do
      member do
        get 'move_up'
        get 'move_down'
      end
    end

    resources :pages do
      member do
        get 'move_up'
        get 'move_down'
      end
    end

    root :to => 'home#index'
  end
  resources :tickets do
    collection do
      post 'preview'
    end
  end

  resources :ticket_replies
  resources :services, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'signup'
      get 'register'
      post 'newaccount'
      get 'failure'
    end
  end
  
  resources :users, :only => [:index] do
    member do
      get 'edit_profile'
      post 'update_profile'
    end

    collection do
      get 'dismiss_newbie_bar'
      get 'undismiss_newbie_bar'
    end
  end

  match '/accounts/:action' => 'accounts'

  match '(/:id)' => 'home#show_page'

  root :to => 'home#index'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if @title.blank? %>
      <title>L2adena</title>
    <% else %>
      <title><%= @title %></title>
    <% end %>
    <%= stylesheet_link_tag 'screen' %>
    <!--[if lt IE 8]>
  <link rel="stylesheet" href="css/blueprint/ie.css" type="text/css" media="screen, projection">
  <![endif]-->
    <%= include_javascripts :default_javascripts %>
    <%= csrf_meta_tag %>
    <style type="text/css">
      div#admin_nav ul {
        list-style:none;
      }

      div#admin_nav ul li {
        padding:5px;
        margin:5px;
        background-color:#F1F5FC;
      }

      div#admin_nav ul li a {
        text-decoration:none;
      }
    </style>
  </head>
  <body>
  <div class="container prepend-top">

    <% flash.each do |key, value| %>
      <div class="<%= key %>"><%= value %></div>
    <% end %>

    <div id="admin_nav" class="span-6">
      <ul>
        <li><%= link_to("Dashboard", {:controller => '/admin/home', :action => 'index'}) %></li>
        <li><%= link_to("Manage Users", {:controller => '/admin/user', :action => 'index'}) %></li>
        <li><%= link_to("Manage News", admin_news_index_path) %></li>
        <li><%= link_to("Manage Pages", admin_pages_path) %></li>
        <li><%= link_to("Support Tickets", admin_tickets_path) %></li>
        <li><%= link_to("Game Server Connection", admin_game_servers_path) %></li>
      </ul>
    </div>

    <div class="span-17 last">
      <%= yield %>
    </div>

    <section id="footer" class="span-24 last">
    <%= link_to("Return to Main Site", root_url) %><br />
    <%= render(:partial => 'shared/footer') %>
    </section>

  </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/xhtml1-strict.dtd">
<html>
  <head>
    <% if @title.blank? %>
      <title>L2adena</title>
    <% else %>
      <title><%= @title %></title>
    <% end %>
    <%= stylesheet_link_tag 'screen' %>
    <!--[if lt IE 8]>
    <link rel="stylesheet" href="css/blueprint/ie.css" type="text/css" media="screen, projection">
    <![endif]-->
    <%= stylesheet_link_tag 'custom' %>
    <%= include_javascripts :default_javascripts %>
    <%= csrf_meta_tag %>
  </head>
  <body>
  <div class="container">
    <div id="header" class="span-24">
      <div id="logo" class="span-5">
        <%= link_to image_tag('l2adena-logo.png', :class => 'span-5'), root_url %>
      </div>
      <div id="server-status" class="span-19 last">
        <%= server_status %>
      </div>
      <div id="badge" class="span-6 right">
        <% if user_signed_in? %>
          <%= image_tag(Gravatar.new(current_user.email).image_url) %>
          <span id="badge-text">
            Signed in as<br />
            <%= current_user.username %> (<%= link_to("Sign Out", signout_path) %>)<br />
            <%= link_to("User Settings", services_path) %>
          </span>
        <% else %>
          You are currently not logged in<br />
          <%= link_to("Sign In", signin_path) %>. New here? <%= link_to("Register", register_services_path) %>
        <% end %>
      </div>
    </div>

    <div class="clear"></div>

  <% if flash.any? %>
    <div id="flash" class="span-24">
      <% flash.each do |key, value| %>
          <div class="<%= key %>"><%= value %></div>
      <% end %>
    </div>
  <% end %>

  <!--[if lt IE 7]> <div style=' clear: both; height: 59px; padding:0 0 0 15px; position: relative;'> <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode"><img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." /></a></div> <![endif]-->

  <% unless session[:hide_newbie_bar] %>
    <%= render(:partial => 'shared/new_user') %>
  <% end %>

    <div id="middle">
      <div id="side-menu" class="span-5">
        <%= render(:partial => 'shared/side_menu') %>
      </div>

      <div id="page-content" class="span-15">
      <%= yield %>
      </div>

      <div id="right-links" class="span-3 last">
        <p><a href="http://l2.hopzone.net/vote.php?site=90008" target="_blank"><img src="http://images.hopzone.net/lineage2/votebanners/lineage2-88x30-3.gif" alt="Vote for HopZone.Net" width="88" height="30" border="0"></a><br /><a href="http://l2.hopzone.net"><img src="http://images.hopzone.net/base/HopZone.gif" alt="HopZone.Net - Free Lineage2 Servers" border="0" width="88" height="1"></a></p>
        <!--Begin GameSites200 Vote--><p><a href="http://www.gamesites200.com/lineage2/in.php?id=28314" target="_blank"><img src="http://www.gamesites200.com/lineage2/vote.gif" alt="Vote on the Lineage 2 Top 200" border="0"></a><br /><a href="http://www.gamesites200.com/lineage2/"><img src="http://www.gamesites200.com/track.gif" alt="Lineage 2 Top 200 - L2 Adena, Clans, Private Servers" border="0"></a></p><!--End Game Sites 200 Code-->
        <a href="http://www.megatop200.com/"><img src="http://www.megatop200.com/button.php?u=Bigcheese" alt="Mega top 200 Private Servers" border="0" /></a>
        <!-- Begin Gtop100 voting code --><br />
<a href="http://www.gtop100.com/in.php?site=64113" title="Top 100 Lineage 2 sites" target="_blank">
<img src="http://www.gtop100.com/images/votebutton.jpg" border="0" alt="Top 100 Lineage 2 sites"></a>
<!-- End Gtop100s voting code -->
      </div>
    </div>
  </div>

  <div id="footer" class="container">
    <div id="footer-content">
      <span class="right">
        <% if current_user and current_user.can_access?(:admin_panel) %>
          <%= link_to("Administrator Panel", {:controller => '/admin/home'}) %><br />
        <% end %>
        <% if session[:hide_newbie_bar] %>
          <%= link_to("Re-show Connection Instructions", undismiss_newbie_bar_users_path) %><br />
        <% end %>
      </span>
    <span class="left">
    &copy; 2011 L2Adena.<br />
    Source code of this site is avaliable @ <%= link_to("github", "https://github.com/ichiro101/l2adena-site", :target => '_blank') %>
    </span>

    <div class="clear"></div>
    </div>
  </div>
  </body>
</html>